package engine;

public enum HeaderType {
    COMMON,
    EMPTY,
    EXTRAPROPERTY,
    AUTHORIZATIONMISSING,
    AUTHORIZATIONEMPTY,
    AUTHORIZATIONINVALID,
    DEVICEIDMISSING,
    DEVICEIDEMPTY,
    DEVICEIDINVALID,
    CONTENTTYPEMISSING,
    CONTENTTYPEEMPTY,
    CONTENTTYPEINVALID,
    SESSION_CREATE_COMMON,
    SESSION_CREATE_EXTRAPROPERTY,
    SESSION_CREATE_AUTHORIZATIONMISSING,
    SESSION_CREATE_AUTHORIZATIONEMPTY,
    SESSION_CREATE_AUTHORIZATIONINVALID,
    SESSION_SERVERS_COMMON,
    SESSION_SERVERS_EXTRAPROPERTY,
    SESSION_SERVERS_AUTHORIZATIONMISSING,
    SESSION_SERVERS_AUTHORIZATIONEMPTY,
    SESSION_SERVERS_AUTHORIZATIONINVALID,
    SESSION_SERVERS_DEVICEIDMISSING,
    SESSION_SERVERS_DEVICEIDEMPTY,
    SESSION_SERVERS_DEVICEIDINVALID,
    SESSION_SERVERS_SESSIONIDMISSING,
    SESSION_SERVERS_SESSIONIDEMPTY,
    SESSION_SERVERS_SESSIONIDINVALID,
    SESSION_OAUTHTOKEN_COMMON,
    SESSION_OAUTHTOKEN_EXTRAPROPERTY,
    SESSION_OAUTHTOKEN_AUTHORIZATIONMISSING,
    SESSION_OAUTHTOKEN_AUTHORIZATIONEMPTY,
    SESSION_OAUTHTOKEN_AUTHORIZATIONINVALID,
    SESSION_OAUTHTOKEN_CONTENTTYPEMISSING,
    SESSION_OAUTHTOKEN_CONTENTTYPEEMPTY,
    SESSION_OAUTHTOKEN_CONTENTTYPEINVALID,
    SESSION_COMMON,
    SESSION_EXTRAPROPERTY,
    SESSION_AUTHORIZATIONMISSING,
    SESSION_AUTHORIZATIONEMPTY,
    SESSION_AUTHORIZATIONINVALID,
    SESSION_LINKING_COMMON,
    SESSION_LINKING_EXTRAPROPERTY,
    SESSION_LINKING_AUTHORIZATIONMISSING,
    SESSION_LINKING_AUTHORIZATIONEMPTY,
    SESSION_LINKING_AUTHORIZATIONINVALID,
    SESSION_LINKING_CONTENTTYPEMISSING,
    SESSION_LINKING_CONTENTTYPEEMPTY,
    SESSION_LINKING_CONTENTTYPEINVALID,

    //--------icons header----------------
    ICONS_AUTHORIZATIONMISSING,
    ICONS_AUTHORIZATIONEMPTY,
    ICONS_AUTHORIZATIONINVALID,
    ICONS_DEVICEIDMISSING,
    ICONS_DEVICEIDEMPTY,
    ICONS_DEVICEIDINVALID,

    //--------geoip header----------------
    GEOIP_XFORWARDEDFORMISSING,
    GEOIP_XFORWARDEDFOREMPTY,
    GEOIP_XFORWARDEDFORINVALID,

    //--------content storage-------------
    CONTENTSTORAGE_CLIENTTOKENMISSING,
    CONTENTSTORAGE_CLIENTTOKENEMPTY,
    CONTENTSTORAGE_CLIENTTOKENINVALID,

    //--------game coaching-------------
    GAMECOACHING_COMMON,
    GAMECOACHING_AUTHORIZATION_MISSING,
    GAMECOACHING_AUTHORIZATION_INVALID,
    GAMECOACHING_AUTHORIZATION_EMPTY,
    GAMECOACHING_CONTENTTYPE_MISSING,
    GAMECOACHING_CONTENTTYPE_INVALID,
    GAMECOACHING_CONTENTTYPE_EMPTY,

    //--------game metadata-------------
    GAMEMETADATA_COMMON,
    GAMEMETADATA_APIKEY_MISSING,
    GAMEMETADATA_APIKEY__INVALID,
    GAMEMETADATA_APIKEY__EMPTY,

    //--------notification-------------
    NOTIFICATION_COMMON_CONTENT_TYPE,
    NOTIFICATION_EXTRA_HEADER,

    //--------image gallery-------------
    IG_HMAC_V1,

    //---------credit suisse-----------
    CN;

}